//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "batches")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub tx: String,
    pub total_inserted: i64,
    pub total_deleted: i64,
    pub batch_size: i64,
    #[sea_orm(column_type = "Text")]
    pub preroot: String,
    #[sea_orm(column_type = "Text")]
    pub postroot: String,
    pub proof: Json,
    pub block: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
