//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "deletions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at_block: i64,
    #[sea_orm(column_type = "Text")]
    pub deleted_in_tx: String,
    #[sea_orm(column_type = "Text", unique)]
    pub pubkey: String,
    #[sea_orm(primary_key, unique)]
    pub id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
